jazzband/icalevents

icalevents/icalparser.py
test/test_icalevents.py

Events have a `description` attribute that was not being used.

Parse event's description attribute

---

icalevents/icalparser.py
test/test_icalparser.py

This PR  addresses the error highlighted in issue #10.
With this PR, when the `BYDAY` portion is present in a rule, the `days` argument of the `timedelta` constructor is calculated. The calculations are done outside of the loop, so they are only done once and then saved to a variable as a `dict`.
The dict is created as follows. Given a rule like this:
```
RRULE:FREQ=WEEKLY;BYDAY=SU,TU,SA
````
We determine that the event is scheduled on Sundays, Tuesdays, and Saturdays. We conclude the following:
```python
{
1: 4,  # From Tue to Sat, the next scheduled day, there are 4 days
5: 1   # From Sat to Sun, the next scheduled day, there is 1 day
6: 2   # From Sat to Sun, the next scheduled day, there are 2 day
}
```
According to the `datetime.datetime.weekday()` function Monday is 0, Tuesday is 1, …

Handle 'BYDAY' property when it is provided in weekly rule

---

icalevents/icalparser.py

The `BYDAY` property of a Rule can appear in `WEEKLY` and in `DAILY` frequencies.
Examples:
```
RRULE:FREQ=WEEKLY;BYDAY=SU,SA
RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR
```
The previous PR only took the `WEEKLY` case into account. This PR now applies the same logic to the `DAILY` frequency case.

Applied BYDAY fix to events using a DAILY FREQ rule

---

icalevents/icaldownload.py
icalevents/icalevents.py
test/test_icalevents.py

Reading events from pure string content is added. It becomes a need when the calendar content is not served from a URL or a file.

Reading Ability of Events from String Content

---

icalevents/icalparser.py

This collects all exception dates stored with a component, and then drops all copies of recurring events, whose start is contained in that list.
Not sure if that is the right criterion, but it works for my test case using an ical generated from Google Calendar.

Fix exdate

---

icalevents/icalparser.py

If an event has a duration instead of an end, the end is computed as start + duration.
Fix exception reported in #18 .

Add support for duration

---

icalevents/icalparser.py
test/test_icalevents.py

This is a low-impact change. My use-case is I need to distinguish between recurring and non-recurring events. Without this attribute there is no way to tell if an event is a single event or part of a recurring series of events.

Add a 'recurring' attribute to Event.

---

requirements.txt

icalevents requires `dateutil` and uses the `dateutil.tz.UTC` convenience, only added in version 2.7 of `dateutil`.
If used with an older version of `dateutil`, the following exception will occur:
```
>>> from icalevents.icalevents import events
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Python36\lib\site-packages\icalevents\icalevents.py", line 3, in <module>
from .icalparser import parse_events
File "C:\Python36\lib\site-packages\icalevents\icalparser.py", line 9, in <module>
from dateutil.tz import UTC, gettz
ImportError: cannot import name 'UTC'
```
Thanks!

Fix 'import UTC' error, caused by outdated requirement

---

icalevents/icalparser.py

In python the default value of an argument gets cached the first
time the function is invoked. Subsequent calls to the function
without specifying the argument will use the same cached default
value again. In this particular case all relative deltas will be
calculated from the now that was cached when the function was
invoked the first time thus leading to a wrong time_left

Fixes wrong default value behaviour in `Event.time_left`

---

icalevents/icalparser.py
test/test_icalparser.py

default_span should be user configurable when using parse_events.
Also, additional components are available in the event such as organizer, uid, and attendees. This patch adds support for these components.

added support for default_span adjustment and additional event components

---

icalevents/icaldownload.py

The library cannot be imported from a directory with
no write permissions as httplib2 fails to create the
cache. If there is an error creating `deafult_http`
fall back to having no cache.
Closes #51

Disable httplib2 cache when no write permission

---

icalevents/icalparser.py

ical reference: https://www.kanzaki.com/docs/ical/class.html
attribute is set true if event is marked as private or confidential
details of the event are usually hidden from others in public calendars

add private event attribute

---

icalevents/icaldownload.py
icalevents/icalevents.py

Allowing users to pass a manually created `Http` object to the download class increases flexibility for various circumstances.
The current implementation does not work when used inside an AWS Lambda as the filesystem is read-only and raises an unhandled IOError.
The changes should be fully backwards compatible.

Initialize default http client for downloader in constructor

---

icalevents/icalparser.py

Sequences are used to know when an single event overrides a recurring event

Support SEQUENCE in ical events

---

icalevents/icalparser.py

This PR contains the same changes as my earlier PR (#53) reworked so that they apply cleanly to the current master. Along the way, I made a few improvements so that all of the tests pass. In this PR:
* Fixed mangling of the timezone see https://github.com/irgangla/icalevents/issues/12#issuecomment-456121570
* Track all of the timezones defined; attempt to map events to the correct timezone
* Ignore dates listed as exceptions (i.e handle EXDATE on recurring events)
* Recompute the start time of recurring events in the current timezone (preventing recurring events from being off by an hour if the recurrence crosses the daylight savings time boundary)
* Make sure that attendee and organizer are always present
I've tried to document the reasoning behind each of the major changes.

A few enhancements to icalevents

---

icalevents/icaldownload.py
test/test_icaldownload.py

AWS Lambda functions are run in a readonly directory, which causes an OSError with icalevents as described in #65. Catching this error and calling httplib2 without cache fixes the problem.

Preventing crash when running on AWS Lambda

---

icalevents/icaldownload.py
test/test_icaldownload.py

Tiny typo with an empty ICS file caused a TypeError exception on the library rather than the intended IOError on the file. Test case included because ... test everything :D

fix: Template on empty/unreadable file exception is a string, not a float

---

icalevents/icalevents.py

I am pretty sure [`datetime`](https://docs.python.org/3/library/datetime.html#date-objects) is intended instead of [`dateutils`](https://pypi.org/project/dateutils/)

Update documentation hint to date type

---

.readthedocs.yaml
docs/conf.py

fixes: https://github.com/jazzband/icalevents/issues/126

docs: add read-the-docs config

---

icalevents/icalparser.py
poetry.lock
pyproject.toml

fixes https://github.com/jazzband/icalevents/issues/144
See https://github.com/collective/icalendar/blob/v6.0.0/CHANGES.rst for the changelog.

fix: icalendar v6 compatibility

---

icalevents/icalevents.py

This condition is always true, so it does not make any sense to have it there.
On the same line, I would also consider replacing `if sort is True:` -> `if sort:`.

Condition always true

---

docs/conf.py
pyproject.toml
setup.py

Due to the replacement of httplib2 and the requirement of icalendar >= 6.0, I bump the next version number to 0.2.0.

chore: Bump version number to 0.2.0

---

setup.py

When replacing httplib2 with urllib3 (#154), I didn't realized I have to change the requirements there, too. This pull request fixes this little mistake.

chore: Fix requirements in setup.py

---

icalevents/icaldownload.py
test/test_icalevents.py

I was surprised to read the `events()` docstring stating:
> :param string_content: iCal content as string
... While not being able to pass a `str`. Here is the error in this case:
```python
Traceback (most recent call last):
File "test.py", line 28, in <module>
events = icalevents.events(
string_content=ics,
...<3 lines>...
sort=True,
)
File "/.../icalevents/icalevents.py", line 55, in events
content = ical_download.data_from_string(string_content, apple_fix=fix_apple)
File "/.../icalevents/icaldownload.py", line 91, in data_from_string
return self.decode(string_content, apple_fix=apple_fix)
~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/.../icalevents/icaldownload.py", line 103, in decode
content = content.decode(encoding)
^^^^^^^^^^^^^^
AttributeError: 'str' object has no …
```

fix: allow `string_content` to be a `str`

---

icalevents/icaldownload.py
test/test_icaldownload.py

`IOError` was merged in `OSError` since Python 3.3 (https://docs.python.org/3/library/exceptions.html#OSError).

fix: replace usage of `IOError` with `OSError`
